apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: school-management-system
  app.kubernetes.io/version: "1.0.0"
