apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sms-uploads-pvc
  namespace: school-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
